### ISSUE TITLE
[bug] Wrong tips and  wrong tips postion  while using Vue2 + elementUi2.x

### ISSUE THREAD

**Issue by emjio** [Simon-He95/vscode-common-intellisense#41]
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/26915891/2ae1ca29-d0cd-4a88-bb80-40d9eb9d48bd)

**Comment by Simon-He95** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

[Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
